### PR TITLE
properly handle String variables argument, plus tests

### PR DESCRIPTION
**Pull request by zopf**
related to issue:
https://github.com/RisingStack/graffiti/issues/19

### CODE REVIEW

**Comment by tothandras** [comment]
Thanks for the PR @zopf! As far as I know you always need to wrap `JSON.parse` in a `try-catch` block. I hope you don't mind if I applied your changes on #23.

**Comment by zopf** [comment]
Hm.  Do we really want to ignore JSON parsing errors?  I was planning to let those bubble up to top-level middleware handlers...

Seems like somehow the user ought to see that their input is improperly structured.

**Comment by tothandras** [comment]
GraphQL will eventually throw some kind of error if the input is not structured properly, but I might be wrong. Is it true that the variables are always a JSON? Relay includes variables too, and [`graffiti-todo`](https://github.com/RisingStack/graffiti-todo) is working fine without this patch.

**Comment by zopf** [comment]
graffiti-todo works because it's making a different call:

```
{
"query":"mutation AddTodoMutation($input_0:addTodoInput!){addTodo(input:$input_0){clientMutationId,...__RelayQueryFragment773nd7g}} fragment __RelayQueryFragment773nd7g on addTodoPayload{changedTodoEdge{cursor,node{id,complete,text}}}",
"variables":{"input_0":{"text":"Testing","complete":false,"clientMutationId":"0"}}
}
```

As you can see above (just captured on a local session with graffiti-todo), variables is sent as a JSON obj, not as a stringified JSON obj.  I think Relay expects to send them that way, and graphql expects to receive them that way.  The only impedance mismatch is with graphiql's constructor.

The `graphql` constructor [definitely needs](http://graphql.org/docs/api-reference-graphql/#graphql) `variables` to be a JSON obj, whereas the `graphiql` constructor [definitely needs](https://github.com/graphql/graphiql) `variables` to be a stringified JSON obj.

You're right that GraphQL will throw an error if the input was incorrectly structured.  If the JSON object is broken, it just won't parse properly, so the `variables` object will stay a string and be treated as not having been provided.  It won't say "bad JSON object at this parse point" or something... just "GraphQL input of type XXX was not provided" or something like that.

Anyway, my vote is that the error should bubble up, as I'm generally against throwing away exceptions (otherwise, why do they get thrown?).  But you guys own the library, I'll defer to your judgement.

**Comment by zopf** [comment]
Here's what the GraphiQL devs did in their express-graphiql implementation:

https://github.com/graphql/express-graphql/blob/master/src/index.js#L248

**Pull request closed without merging**
