### PR TITLE
Added ability to specify a config parameter for graphql hapi routes.

### PR DESCRIPTION
**Pull request by developer-rakeshpaul**
Added ability to specify a config parameter for graphql hapi routes. This is where you configure things like validation, authentication, prerequisites, payload processing, and caching options for your graphql endpoint.

### CODE REVIEW

**Comment by tothandras** [comment]
Thank you! Looks good. Can you add it to the readme too?

**Comment by developer-rakeshpaul** [comment]
sure @tothandras it is done. Could you please review it?

**Comment by tothandras** [comment]
@developer-rakeshpaul sorry, I didn't get an email from github for some reason :/ released with version `3.2.0`

**Comment by developer-rakeshpaul** [comment]
@tothandras 👍

**Pull request merged**
